// <auto-generated />
using System;
using BlazorMyRide.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorMyRide.Server.Migrations
{
    [DbContext(typeof(BlazorMyRideDbContext))]
    [Migration("20230201122806_CustomTable")]
    partial class CustomTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorMyRide.Shared.Custom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Customs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 1, 12, 28, 6, 694, DateTimeKind.Utc).AddTicks(2993),
                            Description = "Battery Repair and Replacement",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 1, 12, 28, 6, 694, DateTimeKind.Utc).AddTicks(2997),
                            Description = "Front side bulbs",
                            Price = 42.66m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
